# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoPodProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoPodProject
  
  pod 'Alamofire' , '~> 4.0'
  pod 'ALomafireImage' , '~> 3.3'
  pod 'AlamafireObjectMapper' , '~> 4.0'

end
